name: integracion continua con node.js

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  ci_to_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: cd ci-test
      - run: npm install
      - run: npm test
      - run: npm run build